language: scala
scala:
   - 2.11.2

language: android
android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra
   
install:
	android update project -p /home/travis/build/emptyflash/CoopDJ
   